services:
  memgraph:
    image: memgraph/memgraph-mage:3.4
    container_name: statespace-memgraph
    ports:
      - "${MEMGRAPH_BOLT_PORT:-7687}:7687"
      - "${MEMGRAPH_LOG_PORT:-7444}:7444"
    environment:
      MEMGRAPH: "--memory-limit=1024 --auth-user-or-role-name-regex=.* --auth-password-permit-null=false"
      MEMGRAPH_USER: ${MEMGRAPH_USER:-memgraph}
      MEMGRAPH_PASSWORD: ${MEMGRAPH_PASSWORD}
    volumes:
      - memgraph_data:/var/lib/memgraph
    networks:
      - statespace
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/7687' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  memgraph-lab:
    image: memgraph/lab:3.4.0
    container_name: statespace-lab
    ports:
      - "${MEMGRAPH_LAB_PORT:-3000}:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph
      QUICK_CONNECT_MG_PORT: 7687
    depends_on:
      - memgraph
    networks:
      - statespace
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  statespace-server:
    build:
      context: .
      dockerfile: packages/memgraph/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
        PORT: ${SERVER_PORT:-4000}
        MEMGRAPH_URL: bolt://memgraph:7687
        MEMGRAPH_USER: ${MEMGRAPH_USER:-memgraph}
        MEMGRAPH_PASSWORD: ${MEMGRAPH_PASSWORD}
        MEMGRAPH_DATABASE_NAME: ${MEMGRAPH_DATABASE_NAME:-memgraph}
        MEMGRAPH_CONNECTION_LIFETIME: ${MEMGRAPH_CONNECTION_LIFETIME:-86400000}
        MEMGRAPH_CONNECTION_TIMEOUT: ${MEMGRAPH_CONNECTION_TIMEOUT:-86400000}
        MEMGRAPH_MAX_CONNECTIONS: ${MEMGRAPH_MAX_CONNECTIONS:-100}
        ENABLE_GRAPHIQL: ${ENABLE_GRAPHIQL:-true}
        ENABLE_LANDING_PAGE: ${ENABLE_LANDING_PAGE:-true}
    container_name: statespace-server
    ports:
      - "${SERVER_PORT:-4000}:4000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 4000
      MEMGRAPH_URL: bolt://memgraph:7687
      MEMGRAPH_USER: ${MEMGRAPH_USER:-memgraph}
      MEMGRAPH_PASSWORD: ${MEMGRAPH_PASSWORD}
      MEMGRAPH_DATABASE_NAME: ${MEMGRAPH_DATABASE_NAME:-memgraph}
      MEMGRAPH_CONNECTION_LIFETIME: ${MEMGRAPH_CONNECTION_LIFETIME:-86400000}
      MEMGRAPH_CONNECTION_TIMEOUT: ${MEMGRAPH_CONNECTION_TIMEOUT:-86400000}
      MEMGRAPH_MAX_CONNECTIONS: ${MEMGRAPH_MAX_CONNECTIONS:-100}
      ENABLE_GRAPHIQL: ${ENABLE_GRAPHIQL:-true}
      ENABLE_LANDING_PAGE: ${ENABLE_LANDING_PAGE:-true}
    depends_on:
      memgraph:
        condition: service_healthy
    networks:
      - statespace
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4000/graphql || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  statespace-mcp:
    build:
      context: .
      dockerfile: packages/mcp/Dockerfile
    container_name: statespace-mcp
    ports:
      - "${MCP_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
    networks:
      - statespace
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  memgraph_data:

networks:
  statespace:
    driver: bridge 