import * as Types from '../../generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type StatesListQueryVariables = Types.Exact<{
  where?: Types.InputMaybe<Types.StateWhere>;
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  offset?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  sort?: Types.InputMaybe<Array<Types.StateSort> | Types.StateSort>;
}>;


export type StatesListQuery = { __typename?: 'Query', states: Array<{ __typename?: 'State', id: string, hash: string, codex: Types.Codex, api_version: string, timestamp_created: any, timestamp_updated?: any | null }> };

export type StatesCreateMutationVariables = Types.Exact<{
  input: Types.StateCreateInput;
}>;


export type StatesCreateMutation = { __typename?: 'Mutation', createStates: { __typename?: 'CreateStatesMutationResponse', states: Array<{ __typename?: 'State', id: string, hash: string, codex: Types.Codex, api_version: string, timestamp_created: any, timestamp_updated?: any | null }>, info: { __typename?: 'CreateInfo', nodesCreated: number, relationshipsCreated: number } } };

export type StatesCreateBatchMutationVariables = Types.Exact<{
  input: Array<Types.StateCreateInput> | Types.StateCreateInput;
}>;


export type StatesCreateBatchMutation = { __typename?: 'Mutation', createStates: { __typename?: 'CreateStatesMutationResponse', states: Array<{ __typename?: 'State', id: string, hash: string, codex: Types.Codex, api_version: string, timestamp_created: any, timestamp_updated?: any | null }>, info: { __typename?: 'CreateInfo', nodesCreated: number, relationshipsCreated: number } } };

export type StatesUpsertMutationVariables = Types.Exact<{
  input: Types.StateUpsertInput;
}>;


export type StatesUpsertMutation = { __typename?: 'Mutation', upsertStates: { __typename?: 'UpsertStatesMutationResponse', states: Array<{ __typename?: 'State', id: string, hash: string, codex: Types.Codex, api_version: string, timestamp_created: any, timestamp_updated?: any | null }>, info: { __typename?: 'UpsertInfo', nodesCreated: number, nodesUpdated: number } } };

export type StatesUpsertBatchMutationVariables = Types.Exact<{
  input: Array<Types.StateUpsertInput> | Types.StateUpsertInput;
}>;


export type StatesUpsertBatchMutation = { __typename?: 'Mutation', upsertStates: { __typename?: 'UpsertStatesMutationResponse', states: Array<{ __typename?: 'State', id: string, hash: string, codex: Types.Codex, api_version: string, timestamp_created: any, timestamp_updated?: any | null }>, info: { __typename?: 'UpsertInfo', nodesCreated: number, nodesUpdated: number } } };

export type StatesCreateTransitionMutationVariables = Types.Exact<{
  input: Types.CreateTransitionInput;
}>;


export type StatesCreateTransitionMutation = { __typename?: 'Mutation', createTransition: { __typename?: 'CreateTransitionMutationResponse', transitions: Array<{ __typename?: 'Transition', id: string, rule_name: string, cost: number, metadata?: string | null, api_version: string, timestamp_created: any, timestamp_updated?: any | null }> } };


export const StatesListDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"states_list"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"where"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"StateWhere"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"limit"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"offset"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateSort"}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"where"},"value":{"kind":"Variable","name":{"kind":"Name","value":"where"}}},{"kind":"Argument","name":{"kind":"Name","value":"limit"},"value":{"kind":"Variable","name":{"kind":"Name","value":"limit"}}},{"kind":"Argument","name":{"kind":"Name","value":"offset"},"value":{"kind":"Variable","name":{"kind":"Name","value":"offset"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}}]} as unknown as DocumentNode<StatesListQuery, StatesListQueryVariables>;
export const StatesCreateDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_create"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateCreateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ListValue","values":[{"kind":"Variable","name":{"kind":"Name","value":"input"}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CreateInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CreateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CreateInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsCreated"}}]}}]} as unknown as DocumentNode<StatesCreateMutation, StatesCreateMutationVariables>;
export const StatesCreateBatchDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_createBatch"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateCreateInput"}}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CreateInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CreateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CreateInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsCreated"}}]}}]} as unknown as DocumentNode<StatesCreateBatchMutation, StatesCreateBatchMutationVariables>;
export const StatesUpsertDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_upsert"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateUpsertInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"upsertStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ListValue","values":[{"kind":"Variable","name":{"kind":"Name","value":"input"}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UpsertInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"UpsertInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"UpsertInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"nodesUpdated"}}]}}]} as unknown as DocumentNode<StatesUpsertMutation, StatesUpsertMutationVariables>;
export const StatesUpsertBatchDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_upsertBatch"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateUpsertInput"}}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"upsertStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UpsertInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"UpsertInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"UpsertInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"nodesUpdated"}}]}}]} as unknown as DocumentNode<StatesUpsertBatchMutation, StatesUpsertBatchMutationVariables>;
export const StatesCreateTransitionDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_createTransition"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateTransitionInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createTransition"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"transitions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"TransitionInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"TransitionInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Transition"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"rule_name"}},{"kind":"Field","name":{"kind":"Name","value":"cost"}},{"kind":"Field","name":{"kind":"Name","value":"metadata"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_created"}},{"kind":"Field","name":{"kind":"Name","value":"timestamp_updated"}}]}}]} as unknown as DocumentNode<StatesCreateTransitionMutation, StatesCreateTransitionMutationVariables>;