import * as Types from '../../generated/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type StatesListQueryVariables = Types.Exact<{
  where?: Types.InputMaybe<Types.StateWhere>;
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  offset?: Types.InputMaybe<Types.Scalars['Int']['input']>;
  sort?: Types.InputMaybe<Array<Types.StateSort> | Types.StateSort>;
}>;


export type StatesListQuery = { __typename?: 'Query', states: Array<{ __typename?: 'State', hash: string, codex: Types.Codex, api_version: string, datetime_created: string, datetime_updated: string }> };

export type StatesCreateMutationVariables = Types.Exact<{
  input: Types.StateCreateInput;
}>;


export type StatesCreateMutation = { __typename?: 'Mutation', createStates: { __typename?: 'CreateStatesMutationResponse', states: Array<{ __typename?: 'State', hash: string, codex: Types.Codex, api_version: string, datetime_created: string, datetime_updated: string }>, info: { __typename?: 'CreateInfo', nodesCreated: number, relationshipsCreated: number } } };

export type StatesCreateBatchMutationVariables = Types.Exact<{
  input: Array<Types.StateCreateInput> | Types.StateCreateInput;
}>;


export type StatesCreateBatchMutation = { __typename?: 'Mutation', createStates: { __typename?: 'CreateStatesMutationResponse', states: Array<{ __typename?: 'State', hash: string, codex: Types.Codex, api_version: string, datetime_created: string, datetime_updated: string }>, info: { __typename?: 'CreateInfo', nodesCreated: number, relationshipsCreated: number } } };

export type StatesUpdateMutationVariables = Types.Exact<{
  where?: Types.InputMaybe<Types.StateWhere>;
  update?: Types.InputMaybe<Types.StateUpdateInput>;
}>;


export type StatesUpdateMutation = { __typename?: 'Mutation', updateStates: { __typename?: 'UpdateStatesMutationResponse', states: Array<{ __typename?: 'State', hash: string, codex: Types.Codex, api_version: string, datetime_created: string, datetime_updated: string }>, info: { __typename?: 'UpdateInfo', nodesCreated: number, nodesDeleted: number, relationshipsCreated: number, relationshipsDeleted: number } } };


export const StatesListDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"states_list"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"where"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"StateWhere"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"limit"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"offset"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"sort"}},"type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateSort"}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"where"},"value":{"kind":"Variable","name":{"kind":"Name","value":"where"}}},{"kind":"Argument","name":{"kind":"Name","value":"limit"},"value":{"kind":"Variable","name":{"kind":"Name","value":"limit"}}},{"kind":"Argument","name":{"kind":"Name","value":"offset"},"value":{"kind":"Variable","name":{"kind":"Name","value":"offset"}}},{"kind":"Argument","name":{"kind":"Name","value":"sort"},"value":{"kind":"Variable","name":{"kind":"Name","value":"sort"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_created"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_updated"}}]}}]} as unknown as DocumentNode<StatesListQuery, StatesListQueryVariables>;
export const StatesCreateDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_create"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateCreateInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ListValue","values":[{"kind":"Variable","name":{"kind":"Name","value":"input"}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CreateInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_created"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CreateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CreateInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsCreated"}}]}}]} as unknown as DocumentNode<StatesCreateMutation, StatesCreateMutationVariables>;
export const StatesCreateBatchDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_createBatch"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"ListType","type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"StateCreateInput"}}}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"CreateInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_created"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CreateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CreateInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsCreated"}}]}}]} as unknown as DocumentNode<StatesCreateBatchMutation, StatesCreateBatchMutationVariables>;
export const StatesUpdateDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"states_update"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"where"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"StateWhere"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"update"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"StateUpdateInput"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateStates"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"where"},"value":{"kind":"Variable","name":{"kind":"Name","value":"where"}}},{"kind":"Argument","name":{"kind":"Name","value":"update"},"value":{"kind":"Variable","name":{"kind":"Name","value":"update"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"states"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"StateInfo"}}]}},{"kind":"Field","name":{"kind":"Name","value":"info"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"UpdateInfo"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"StateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"State"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"hash"}},{"kind":"Field","name":{"kind":"Name","value":"codex"}},{"kind":"Field","name":{"kind":"Name","value":"api_version"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_created"}},{"kind":"Field","name":{"kind":"Name","value":"datetime_updated"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"UpdateInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"UpdateInfo"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"nodesCreated"}},{"kind":"Field","name":{"kind":"Name","value":"nodesDeleted"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsCreated"}},{"kind":"Field","name":{"kind":"Name","value":"relationshipsDeleted"}}]}}]} as unknown as DocumentNode<StatesUpdateMutation, StatesUpdateMutationVariables>;