const {
  NODE_ENV = "development",
  PORT = 4000,
  MEMGRAPH_CONNECTION_LIFETIME = 1000 * 60 * 60 * 24,
  MEMGRAPH_CONNECTION_TIMEOUT = 1000 * 60 * 60 * 24,
  MEMGRAPH_MAX_CONNECTIONS = 100,
  MEMGRAPH_URL = "bolt://localhost:7687",
  MEMGRAPH_USER = "neo4j",
  MEMGRAPH_PASSWORD,
  MEMGRAPH_DATABASE_NAME = "memgraph",
  ENABLE_GRAPHIQL = "true",
  ENABLE_LANDING_PAGE = "true",
} = process.env;

if (!MEMGRAPH_PASSWORD) {
  throw new Error("MEMGRAPH_PASSWORD is not set");
}

export {
  NODE_ENV,
  PORT,
  MEMGRAPH_CONNECTION_LIFETIME,
  MEMGRAPH_CONNECTION_TIMEOUT,
  MEMGRAPH_MAX_CONNECTIONS,
  MEMGRAPH_URL,
  MEMGRAPH_USER,
  MEMGRAPH_PASSWORD,
  MEMGRAPH_DATABASE_NAME,
  ENABLE_GRAPHIQL,
  ENABLE_LANDING_PAGE,
};
